# Generated by Django 4.2 on 2025-12-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obra de Arte', 'verbose_name_plural': 'Galería de Obras'},
        ),
        migrations.RemoveField(
            model_name='obra',
            name='precio',
        ),
    ]
